# Generated by Django 4.1 on 2023-04-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PZ', 'Pizza'), ('DR', 'Drinks'), ('SC', 'Sauce'), ('SF', 'Side Food')], default='PZ', max_length=2)),
                ('name', models.CharField(max_length=225)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('maxQty', models.IntegerField(default=0)),
                ('pricePerUnit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('caloriesPerUnit', models.DecimalField(decimal_places=2, default='1000.50', max_digits=6)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
    ]
