# Generated by Django 4.1 on 2023-05-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_staff_rosters'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CF', 'Confirmed'), ('FF', 'Fullfiled'), ('CC', 'CANCELED')], default='CF', max_length=2),
        ),
    ]
