# Generated by Django 4.1 on 2023-05-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_url',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CF', 'Confirmed'), ('FF', 'Fullfiled'), ('CC', 'Canceled')], default='CF', max_length=2),
        ),
    ]
