# Generated by Django 4.1 on 2023-04-16 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_adminuser_customer_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('stripe_token', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('MON', ''), ('TUE', ''), ('WED', ''), ('THU', ''), ('FRI', ''), ('SAT', ''), ('SUN', '')], max_length=3)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('noStaffs', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='loyalPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='roster',
            constraint=models.CheckConstraint(check=models.Q(('end__gt', models.F('start'))), name='check_time'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.customer'),
        ),
        migrations.AddField(
            model_name='staff',
            name='rosters',
            field=models.ManyToManyField(to='api.roster'),
        ),
    ]
