# Generated by Django 4.1 on 2023-04-17 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_admin_alter_customer_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-dateAdded',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
